bread/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("recipes.urls")),
]

if settings.DEBUG:
    urlpatterns.append(path("__debug__/", include("debug_toolbar.urls")))

recipes/urls.py
# Copyright 2022 Aleksandr Soloshenko
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from django.views.decorators.cache import cache_page

from . import views

app_name = "recipes"
urlpatterns = [
    path("", cache_page(60)(views.RecipesListView.as_view()), name="list"),
    path(
        "recipe/<int:pk>/",
        cache_page(3600)(views.RecipeDetailsView.as_view()),
        name="details",
    ),
    path(
        "recipe/<int:recipe_id>/comment",
        views.CommentAddView.as_view(),
        name="comment_add",
    ),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

recipes/models.py
import os
from decimal import Decimal
from io import BytesIO

from django.core.files import File
from django.db import models
from PIL import Image

from .storage import photoStorage

# Create your models here.


class TimestampedModel(models.Model):
    created_at = models.DateTimeField("создан", auto_now_add=True, editable=False)
    updated_at = models.DateTimeField("обновлен", auto_now=True, editable=False)

    class Meta:
        abstract = True


class Comment(TimestampedModel):
    STATE_NEW = "new"
    STATE_ACCEPTED = "accepted"
    STATE_REJECTED = "rejected"

    STATE_CHOICES = [
        (STATE_NEW, "новый"),
        (STATE_ACCEPTED, "принят"),
        (STATE_REJECTED, "отклонен"),
    ]

    state = models.CharField(
        "состояние", max_length=8, choices=STATE_CHOICES, blank=False, default=STATE_NEW
    )
    text = models.TextField("текст", blank=False)
    # author = models.ForeignKey(
    #     "auth.User", on_delete=models.CASCADE, related_name="comments"
    # )
    recipe = models.ForeignKey(
        "Recipe",
        on_delete=models.CASCADE,
        related_name="comments",
        verbose_name="рецепт",
    )

    def __str__(self):
        return self.text

    class Meta:
        verbose_name = "комментарий"
        verbose_name_plural = "комментарии"
        ordering = ("-created_at",)


class Measure(TimestampedModel):
    name = models.CharField("наименование", max_length=32, unique=True)
    short_name = models.CharField("краткое наименование", max_length=32)
    volume = models.PositiveIntegerField("объем в миллилитрах", null=True, blank=True)

    def __str__(self):
        if self.volume:
            return f"{self.name} ({self.volume} мл)"
        else:
            return self.name

    class Meta:
        ordering = ["name"]
        verbose_name = "единицу измерения"
        verbose_name_plural = "единицы измерения"


class Ingredient(TimestampedModel):
    name = models.CharField(max_length=64, unique=True)
    measures = models.ManyToManyField(Measure, through="MeasureWeight")

    def __str__(self) -> str:
        return self.name

    class Meta:
        ordering = ["name"]
        verbose_name = "ингредиент"
        verbose_name_plural = "ингредиенты"


class MeasureWeight(models.Model):
    ingredient = models.ForeignKey(Ingredient, on_delete=models.CASCADE)
    measure = models.ForeignKey(Measure, on_delete=models.CASCADE)
    weight = models.FloatField("вес в граммах")

    def __str__(self) -> str:
        return f"1 {self.measure.short_name} {self.ingredient.name} = {self.weight} гр."

    class Meta:
        constraints = [
            models.UniqueConstraint(
                fields=["ingredient", "measure"], name="unique_ingredient_measure"
            )
        ]
        verbose_name = "вес ЕИ"
        verbose_name_plural = "вес ЕИ"


class Program(TimestampedModel):
    name = models.CharField("наименование", max_length=64, unique=True)
    duration = models.DurationField("продолжительность, мин")

    def __str__(self) -> str:
        return f"{self.name} ({self.duration})"

    class Meta:
        ordering = ["name"]
        verbose_name = "программу"
        verbose_name_plural = "программы"


class Category(TimestampedModel):
    name = models.CharField("наименование", max_length=64)

    def __str__(self) -> str:
        return self.name

    class Meta:
        ordering = ["name"]
        verbose_name = "категория"
        verbose_name_plural = "категории"


class Recipe(TimestampedModel):
    CRUST_LIGHT = "light"
    CRUST_MEDIUM = "medium"
    CRUST_DARK = "dark"

    CRUST_COLOR_CHOICES = [
        (CRUST_LIGHT, "Светлая"),
        (CRUST_MEDIUM, "Средняя"),
        (CRUST_DARK, "Темная"),
    ]

    category = models.ForeignKey(
        Category,
        on_delete=models.RESTRICT,
        verbose_name="категория",
        related_name="recipes",
        blank=False,
        null=True,
    )
    name = models.CharField("наименование", max_length=64, unique=True)
    crust = models.CharField(
        "корочка", max_length=8, choices=CRUST_COLOR_CHOICES, blank=True
    )
    description = models.TextField("описание")
    program = models.ForeignKey(
        Program, on_delete=models.RESTRICT, verbose_name="программа"
    )
    weight = models.PositiveIntegerField("вес в граммах")
    photo = models.ImageField("фотография", blank=True, null=True, storage=photoStorage)
    thumbnail = models.ImageField(
        "фотография", blank=True, null=True, storage=photoStorage, editable=False
    )
    steps = models.TextField("подготовка", blank=True)
    after = models.TextField("завершение", blank=True)

    def save(self, *args, **kwargs) -> None:

        if self.photo and not (
            self.thumbnail
            and self.thumbnail.name.startswith(self.photo.name + "_thumb")
        ):
            buffer = BytesIO()

            img = Image.open(self.photo)
            img.thumbnail(
                (
                    256,
                    256,
                )
            )
            img.save(buffer, "JPEG")

            self.thumbnail = File(
                buffer, os.path.splitext(self.photo.name)[0] + "_thumb.jpg"
            )
        super().save(*args, **kwargs)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ["name"]
        verbose_name = "рецепт"
        verbose_name_plural = "рецепты"


class RecipeIngredient(models.Model):
    recipe = models.ForeignKey(
        Recipe,
        on_delete=models.CASCADE,
        verbose_name="рецепт",
        related_name="ingredients",
    )
    position = models.PositiveIntegerField("№", editable=False)
    ingredient = models.ForeignKey(
        Ingredient, on_delete=models.RESTRICT, verbose_name="ингредиент"
    )
    quantity = models.DecimalField("кол-во", max_digits=10, decimal_places=3)
    measure = models.ForeignKey(Measure, on_delete=models.RESTRICT, verbose_name="ЕИ")
    comment = models.CharField("комментарий", max_length=64, blank=True)

    def volume(self):
        return self.quantity * self.measure.volume

    def weight(self):
        for mw in self.ingredient.measureweight_set.all():
            if mw.measure == self.measure and mw.ingredient == self.ingredient:
                return self.quantity * Decimal(mw.weight)
        return None

    def save(self, *args, **kwargs):
        self.position = (
            RecipeIngredient.objects.all().filter(recipe=self.recipe).count() + 1
        )
        super().save(*args, **kwargs)

    def __str__(self):
        return f"{self.quantity} {self.measure.name} {self.ingredient.name}"

    class Meta:
        constraints = [
            models.UniqueConstraint(
                fields=["recipe", "position"], name="unique_recipeingredient_position"
            )
        ]
        ordering = ["recipe", "position"]
        verbose_name = "ингредиент рецепта"
        verbose_name_plural = "ингредиенты рецепта"

recipes/forms.py
# Copyright 2022 Aleksandr Soloshenko
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

from django import forms

from . import models


class CommentForm(forms.ModelForm):
    class Meta:
        model = models.Comment
        fields = ["text"]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["text"].widget.attrs["placeholder"] = "Введите комментарий"

recipes/views.py
# Copyright 2022 Aleksandr Soloshenko
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

from typing import Any, Dict

from django.contrib.messages.views import SuccessMessageMixin
from django.http import (
    HttpRequest,
    HttpResponse,
    HttpResponseBadRequest,
    HttpResponseNotFound,
)
from django.shortcuts import get_object_or_404
from django.urls import reverse
from django.views.generic import DetailView, ListView
from django.views.generic.edit import CreateView

from . import forms, models


# Create your views here.
class RecipesListView(ListView):
    model = models.Recipe

    def get_queryset(self):
        category_id = self.request.GET.get("category")

        query = models.Recipe.objects
        if category_id:
            query = query.filter(category__id=category_id)

        return query.prefetch_related("category", "ingredients__ingredient").all()


class RecipeDetailsView(DetailView):
    model = models.Recipe

    def get_context_data(self, **kwargs) -> Dict[str, Any]:
        kwargs["comment_form"] = forms.CommentForm()

        data = super().get_context_data(**kwargs)

        data["comments"] = models.Comment.objects.filter(
            recipe=data["object"], state=models.Comment.STATE_ACCEPTED
        )

        return data

    def get_object(self):
        pk = self.kwargs.get(self.pk_url_kwarg)

        return get_object_or_404(
            models.Recipe.objects.filter(pk=pk)
            .select_related("category", "program")
            .prefetch_related(
                "ingredients__ingredient",
                "ingredients__ingredient__measureweight_set__measure",
                "ingredients__measure",
            )
        )


class CommentAddView(SuccessMessageMixin, CreateView):
    model = models.Comment
    form_class = forms.CommentForm
    success_message: str = "Комментарий добавлен. Он будет отображен после модерации."

    def post(self, request: HttpRequest, *args, **kwargs) -> HttpResponse:
        if "recipe_id" not in kwargs:
            return HttpResponseBadRequest()
        recipe_id = kwargs["recipe_id"]
        self.recipe = models.Recipe.objects.get(pk=recipe_id)
        if not self.recipe:
            return HttpResponseNotFound()

        return super().post(request, *args, **kwargs)

    def form_valid(self, form: forms.CommentForm):
        form.instance.recipe = self.recipe
        # form.instance.user = self.request.user
        return super().form_valid(form)

    def get_success_url(self):
        return reverse("recipes:details", kwargs={"pk": self.recipe.pk})

recipes/templates/recipes/base.html
<!doctype html>
<html>
  <head>
    <title>{% block title %}{% endblock %} - Хлебопекарь</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/semantic-ui@2.4.2/dist/semantic.min.css">
  </head>
  <body>
    <section>
      <header class="ui top attached segment">
        {% block header %}{% endblock %}
      
        
      </header>
      <div class="ui bottom attached segment">
        {% block content %}{% endblock %}
      </div>
    </section>
    <script src="https://cdn.jsdelivr.net/npm/semantic-ui@2.4.2/dist/semantic.min.js"></script>
  </body>
</html>

recipes/templates/recipes/recipe_detail.html
{% extends 'recipes/base.html' %}
{% load static %}

{% block header %}
<h1>
  <a href="{% url 'recipes:list' %}"><i class="ui arrow left icon"></i></a> {% block title %}{{ object.name }}{% endblock %}
</h1>
{% endblock %}

{% block content %}
<div class="ui items">
  <div class="item">
    <div class="image">
      {% if recipe.photo %}
      <a href="{{recipe.photo.url}}" target="_blank"><img class="ui image" src="{{recipe.thumbnail.url}}" /></a>
      {% else %}
      <img class="ui image" src="{% static 'recipes/no-photo.jpg'%}">
      {% endif %}
    </div>
    <div class="content">
      <a class="header">{{ object.name }}</a>
      <div class="extra">
        <div class="ui mini label">{{ object.program.name }}</div>
        <div class="ui mini label"><i class="ui clock icon"></i>{{ object.program.duration }}</div>
        <div class="ui mini label"><i class="ui balance scale icon"></i>{{ object.weight }} г</div>
        {% if object.crust %}
        <div class="ui mini label"><i class="ui adjust icon"></i>{{ object.get_crust_display }}</div>
        {% endif %}
      </div>
      <div class="meta">
        <p>{{ object.description }}</p>
        <p>{{ object.steps|linebreaks }}</p>
      </div>
      <div class="description">
        <table class="ui very basic celled table">
          <thead>
            <tr>
              <th>Ингредиент</th>
              <th>Кол-во</th>
              <th>Объем</th>
              <th>Вес</th>
              <th>Комментарий</th>
            </tr>
          </thead>
          <tbody>
            {% for ingredient in recipe.ingredients.all|dictsort:"position" %}
            <tr>
              <td>{{ ingredient.ingredient.name }}</td>
              <td class="ui right aligned">{{ ingredient.quantity }} {{ ingredient.measure.short_name }}</td>
              <td class="ui right aligned">
                {% if ingredient.measure.volume %}
                  {{ ingredient.volume }} мл
                {% endif %}
              </td>
              <td class="ui right aligned">
                {% if ingredient.weight %}
                  {{ ingredient.weight }} г
                {% endif %}
              </td>
              <td class="ui right aligned">
                {% if ingredient.weight %}
                  {{ ingredient.comment }}
                {% endif %}
              </td>
            </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
      <div class="meta">
        <p>{{ object.after }}</p>
      </div>
      <div class="meta">
        <h3 class="ui dividing header">Комментарии</h3>
        {% if messages %}
            {% for message in messages %}
              {% if message.level == DEFAULT_MESSAGE_LEVELS.SUCCESS %}
              <div class="ui success message">
                <div class="header">
                  Успех
                </div>
                <p>{{ message }}</p>
              </div>
              {% endif %}
            {% endfor %}
        {% else %}
          <form method="post" action={% url 'recipes:comment_add' recipe_id=object.pk %} class="ui form">
            {% csrf_token %}
            {{ form.non_field_errors }}
            <div class="field">
              {{ comment_form.text }}
            </div>
            {{ form.text.errors }}
            <input class="ui fluid accept button" type="submit" value="Отправить">
        </form>
        {% endif %}

        <div class="ui feed">
          {% for comment in comments.all %}
          <div class="event">
            <div class="content">
              <div class="summary">
                <a class="user">Аноним</a> написал
                <div class="date">
                  {{ comment.created_at|date:"d.m.Y H:i" }}
                </div>
              </div>
              <div class="extra text">
                {{ comment.text }}
              </div>
            </div>
          </div>
          {% endfor %}
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

recipes/templates/recipes/recipe_list.html
{% extends 'recipes/base.html' %}
{% load static %}

{% block header %}
<h1>{% block title %}Рецепты{% endblock %}</h1>
{% endblock %}

{% block content %}
<div class="ui cards">
  {% for recipe in object_list %}
  <a class="ui card" href="{% url 'recipes:details' recipe.id %}">
    <div class="image">
      {% if recipe.thumbnail %}
      <img src="{{recipe.thumbnail.url}}">
      {% else %}
      <img src="{% static 'recipes/no-photo.jpg'%}">
      {% endif %}
    </div>
    <div class="ui content">
      <header class="ui header">
        {{ recipe.name }}
      </header>
      <div class="ui meta">
        {% for ingredient in recipe.ingredients.all|dictsort:"position"|slice:":5" %}
        <div class="ui mini label">{{ ingredient.ingredient.name }}</div>
        {% endfor %}
      </div>
      <div class="ui description">
        {{ recipe.description|truncatewords:25 }}
      </div>
      <div class="ui meta">
        {% if recipe.category %}
        <div class="ui mini label">
          {{ recipe.category.name}}
        </div>
        {% endif %}
      </div>
    </div>
  </a>
  {% endfor %}
</div>
{% endblock %}